apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: my-application
build:
  artifacts:
  - image: nextjs-app-image
    context: app
  - image: rust-api-image
    context: api
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
