apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
spec:
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: rust-api-image
        ports:
        - containerPort: 3001
