apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
spec:
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: rust-api-image
        ports:
        - containerPort: 3001
apiVersion: v1
kind: Service
metadata:
  name: rust-api-service
spec:
  type: LoadBalancer
  selector:
    app: rust-api
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
