apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: nextjs-app-image
        ports:
        - containerPort: 3000
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  type: LoadBalancer
  selector:
    app: nextjs-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
